export const ITEM_CATEGORIES = [
  { value: "furniture", label: "Furniture" },
  { value: "home-decor", label: "Home & Décor" },
  { value: "kitchen-dining", label: "Kitchen & Dining" },
  { value: "electronics", label: "Electronics" },
  { value: "tools-hardware", label: "Tools & Hardware" },
  { value: "lawn-garden", label: "Lawn & Garden" },
  { value: "clothing-shoes", label: "Clothing & Shoes" },
  { value: "kids-baby", label: "Kids & Baby" },
  { value: "toys-games", label: "Toys & Games" },
  { value: "sports-outdoors", label: "Sports & Outdoors" },
  { value: "books-media", label: "Books & Media" },
  { value: "collectibles-antiques", label: "Collectibles & Antiques" },
  { value: "jewelry-accessories", label: "Jewelry & Accessories" },
  { value: "automotive", label: "Automotive" },
  { value: "pet-supplies", label: "Pet Supplies" },
  { value: "crafts-hobbies", label: "Crafts & Hobbies" },
  { value: "free-stuff", label: "Free Stuff" },
  { value: "other", label: "Other" },
];
